// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Run `pnpm icons` to regenerate.

export const LOGO_ASSETS = {
  badge: { src: "/brand/badge.png", width: 1118, height: 921 },
  wordmark: { src: "/brand/wordmark.png", width: 1112, height: 295 },
  mark: { src: "/brand/mark.png", width: 90, height: 92 },
} as const;
